namespace Igorious.StardewValley.DynamicApi2.Constants
{
    public enum CategoryID
    {
        Undefined = 0,
        Greens = -81,
        Gem = -2,
        Vegetable = -75,
        Fish = -4,
        Eggs = -5,
        Milks = -6,
        Cooking = -7,
        Crafting = -8,
        BigCraftable = -9,
        Fruits = -79,
        Seeds = -74,
        Minerals = -12,
        Flowers = -80,
        Meat = -14,
        MetalResources = -15,
        BuildingResources = -16,
        SellAtPierres = -17,
        SellAtPierresAndMarnies = -18,
        Fertilizer = -19,
        Junk = -20,
        Baits = -21,
        Tackle = -22,
        SellAtFishShop = -23,
        Furniture = -24,
        Ingredients = -25,
        ArtisanGoods = -26,
        Syrup = -27,
        MonsterLoot = -28,
        Equipment = -29,
        Hat = -95,
        Ring = -96,
        Weapon = -98,
        Boots = -97,
        Tool = -99,
    }
}